repos:
  - repo: local
    hooks:
      - id: ruff-warning
        name: ruff warning only
        entry: bash -c 'ruff check "$@" --exit-zero' --
        language: system
        types: [python]
        verbose: true

      - id: ruff-format-warning
        name: ruff format warning only
        entry: bash -c 'ruff format "$@" --check || true' --
        language: system
        types: [python]
        verbose: true

      - id: check-yaml-warning
        name: check yaml warning only
        entry: bash -c 'check-yaml "$@" || true' --
        language: python
        types: [yaml]
        additional_dependencies: [pre-commit-hooks]
        verbose: true

      - id: check-toml-warning
        name: check toml warning only
        entry: bash -c 'check-toml "$@" || true' --
        language: python
        types: [toml]
        additional_dependencies: [pre-commit-hooks]
        verbose: true

      - id: check-added-large-files-warning
        name: check added large files warning only
        entry: bash -c 'check-added-large-files "$@" || true' --
        language: python
        pass_filenames: true
        additional_dependencies: [pre-commit-hooks]
        verbose: true